name: Train Model

on:
  workflow_call:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          python -m pip install --upgrade pip
          pip install -r 06-cicd/requirements.txt

      - run: |
          cd 06-cicd
          python train.py

      - uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: 06-cicd/models/